# Generated by Django 4.0.3 on 2022-04-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почтовый адрес')),
                ('short_intro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткая информациия')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('social_github', models.CharField(blank=True, max_length=250, null=True, verbose_name='Профиль в GitHub')),
                ('social_twitter', models.CharField(blank=True, max_length=250, null=True, verbose_name='Профиль в Twitter')),
                ('social_youtube', models.CharField(blank=True, max_length=250, null=True, verbose_name='Профиль в YouTube')),
                ('social_facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='Профиль в Facebook')),
                ('social_linkedin', models.CharField(blank=True, max_length=250, null=True, verbose_name='Профиль в LinkedIn')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
