# Generated by Django 4.0.3 on 2022-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_skills_skill_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Персональный сайт'),
        ),
    ]
